import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: '✨ 快速上手',
      items: [{type: 'autogenerated', dirName: 'get-start'}],
    },
    'overview',
    'inspiration',
    'schedule',
    'device-management',
    'api-token',
    'account',
    'orphan-images',
    {
      type: 'category',
      label: '⚙️ 网站设置',
      link: {
        type: 'generated-index',
        title: '网站设置',
        description: '按 Waken-wa-web 真实的基础 / 进阶设置页签整理站点配置。',
      },
      items: [
        {
          type: 'category',
          label: '基础',
          link: {
            type: 'generated-index',
            title: '基础',
            description: '对应后台设置页的基础页签。',
          },
          items: [
            {
              type: 'doc',
              id: 'site-settings/basic',
              label: '网页配置',
            },
          ],
        },
        {
          type: 'category',
          label: '进阶',
          link: {
            type: 'generated-index',
            title: '进阶',
            description: '对应后台设置页的进阶页签。',
          },
          items: [
            {
              type: 'doc',
              id: 'site-settings/platform',
              label: '平台与访问',
            },
            {
              type: 'doc',
              id: 'site-settings/frontend',
              label: '前台展示',
            },
            {
              type: 'doc',
              id: 'site-settings/runtime',
              label: '运行时行为',
            },
            {
              type: 'doc',
              id: 'site-settings/import-export',
              label: '导入与导出',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
