import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: '✨ 快速上手',
      items: [{type: 'autogenerated', dirName: 'get-start'}],
    },
    'overview',
    'inspiration',
    'schedule',
    'device-management',
    'api-token',
    'account',
    'orphan-images',
    {
      type: 'category',
      label: '⚙️ 网站设置',
      items: [{type: 'autogenerated', dirName: 'site-settings'}],
    },
  ],
};

export default sidebars;
